### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-multitenancy#1]
CUBA addon: https://github.com/cuba-platform/multitenancy-addon

## Progress

2021-06-22: 99%

- [x] Migrate business logic to the new API.
- [x] Create an approach for setting tenant id into CurrentAuthentification
- [x] Replace the user entity listener mechanism with another.
- [x] Migrate UI to the new screen API.
- [x] Adopt query modification (filtering by tenant) to Jmix API.
- [x] Remove deprecated API.
- [x] Adopt predefined multitenancy roles.
- [x] REST/Backend UI authentication by the tenant.
- [x] Internal testing (create tenant, management tenant, assignment users in the tenant, set tenant id into CurentAuthentication via UI login and rest auth)
- [x] Change after code review
- [x] Create and publish sample project
- [x] Move old tests from Cuba addon and create new tests if needed
- [x] Review sample project

**Comment by andreysubbotin** [comment]
See addon [readme](https://github.com/Haulmont/jmix-multitenancy/blob/master/README.md) and [sample project](https://github.com/jmix-projects/multitenancy_sample) .

**Comment by maistrenkoIulia** [comment]
all found problems posted as separate issues
