### ISSUE TITLE
Incorrect generation of tenant id in case user with role = tenant admin creates new tenant

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-multitenancy#11]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3119-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

create user with tenant, with role = tenant admin
login by user>Tenant create>fill all fields (tenant name)> ok
AR:
![image](https://user-images.githubusercontent.com/66992566/123091061-f5faa280-d439-11eb-8bcd-0917008e84dc.png)

ER: Tenant id should be available for user or it should be generated automatically correctly

**Comment by andreysubbotin** [comment]
Tenant entity should be in read-only mode for tenant admin role

**Comment by maistrenkoIulia** [comment]
1.1 - ok

**Comment by maistrenkoIulia** [comment]
1.0 - ok
