### ISSUE TITLE
Login with tenantId URL parameter does not work

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-multitenancy#23]
- Run attached application: [demo.zip](https://github.com/Haulmont/jmix-multitenancy/files/8041779/demo.zip)
- Open new browser tab and enter `http://localhost:8080/#login?tenantId=t1` in address, press Enter
- The URL is changed to `http://localhost:8080/#login`. Now you cannot login by entering just user name (`u1`), you need the full name like `t1|u1`.

See [docs](https://docs.jmix.io/jmix/multitenancy/index.html#tenant-users) and [forum topic](https://forum.jmix.ru/t/ne-otrabatyvaet-vhod-po-sokrashhyonnomu-imeni-polzovatelya-s-ispolzovaniem-parametra-tenantid/306).

**Comment by glebfox** [comment]
Will be fixed in Haulmont/jmix-ui#787

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - verified
